// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCVUcab.Persistence.Database;

#nullable disable

namespace RCVUcab.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220722025825_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RCVUcab.Persistence.Entities.CotizacionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CotizacionEstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Incidente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Proveedor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Taller")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("float");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id_Incidente" }, "IX_Cotizacion_IdIncidente");

                    b.HasIndex(new[] { "Id_Proveedor" }, "IX_Cotizacion_IdProveedor");

                    b.HasIndex(new[] { "Id_Taller" }, "IX_Cotizacion_IdTaller");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.FacturaEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_OrdenDeCompraID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ID_OrdenDeCompraID");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.IncidenteEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Administrador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Perito")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeritoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PeritoId");

                    b.HasIndex(new[] { "Id_Perito" }, "IX_Incidente_IdProveedor");

                    b.HasIndex(new[] { "Id_Administrador" }, "IX_ProveedorMarca_IdMarca");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.MarcaEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.OrdenDeCompraEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Administrador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_CotizacionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Id_CotizacionId");

                    b.HasIndex(new[] { "Id_Administrador" }, "IX_OrdernDeCompra_IdAdministrador");

                    b.ToTable("OrdenesDeCompra");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaCotizacionEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descuento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Cotizacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Pieza")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PiezaEstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("TiempoDeEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Id_Cotizacion" }, "IX_PiezaCotizacion_IdCotizacion");

                    b.HasIndex(new[] { "Id_Pieza" }, "IX_PiezaCotizacion_IdPieza");

                    b.ToTable("PiezasCotizaciones");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaMarcaEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Marca")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Pieza")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Id_Marca" }, "IX_PiezaMarca_IdMarca");

                    b.HasIndex(new[] { "Id_Pieza" }, "IX_PiezaMarca_IdPieza");

                    b.ToTable("PiezasMarcas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PolizaEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Admin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoPoliza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Id_Admin" }, "IX_Poliza_IdAdmin");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PropietarioEntity", b =>
                {
                    b.Property<string>("CedulaRif")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Poliza")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CedulaRif");

                    b.HasIndex(new[] { "Id_Poliza" }, "IX_Propietario_IdPoliza");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.ProveedorEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TallerID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("TallerID")
                        .IsUnique()
                        .HasFilter("[TallerID] IS NOT NULL");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.ProveedorMarcaEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Marca")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Proveedor")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Id_Marca" }, "IX_ProveedorMarca_IdMarca")
                        .HasDatabaseName("IX_ProveedorMarca_IdMarca1");

                    b.HasIndex(new[] { "Id_Proveedor" }, "IX_ProveedorMarca_IdProveedor");

                    b.ToTable("ProveedoresMarcas");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.TallerEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Talleres");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.UsuarioEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.VehiculoEntity", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Marca")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Propietario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeEjes")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDePuestos")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("SerialCarroceria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Placa");

                    b.HasIndex(new[] { "Id_Marca" }, "IX_Vehiculo_IdMarca");

                    b.HasIndex(new[] { "Id_Propietario" }, "IX_Vehiculo_IdPropietario");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.VehiculoIncidenteTallerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id_Incidente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Pieza")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Taller")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id_Vehiculo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Id_Incidente" }, "IX_VehiculoIncidenteTaller_IdIncidente");

                    b.HasIndex(new[] { "Id_Pieza" }, "IX_VehiculoIncidenteTaller_IdPieza");

                    b.HasIndex(new[] { "Id_Taller" }, "IX_VehiculoIncidenteTaller_IdTaller");

                    b.HasIndex(new[] { "Id_Vehiculo" }, "IX_VehiculoIncidenteTaller_IdVehiculo");

                    b.ToTable("VehiculosIncidentesTalleres");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.CotizacionEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.IncidenteEntity", "Incidente")
                        .WithMany("Cotizacion")
                        .HasForeignKey("Id_Incidente");

                    b.HasOne("RCVUcab.Persistence.Entities.ProveedorEntity", "Proveedor")
                        .WithMany("Cotizacion")
                        .HasForeignKey("Id_Proveedor");

                    b.HasOne("RCVUcab.Persistence.Entities.TallerEntity", "Taller")
                        .WithMany("CotizacionT")
                        .HasForeignKey("Id_Taller");

                    b.Navigation("Incidente");

                    b.Navigation("Proveedor");

                    b.Navigation("Taller");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.FacturaEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.OrdenDeCompraEntity", "ID_OrdenDeCompra")
                        .WithMany()
                        .HasForeignKey("ID_OrdenDeCompraID");

                    b.Navigation("ID_OrdenDeCompra");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.IncidenteEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.UsuarioEntity", "Administrador")
                        .WithMany("Incidente")
                        .HasForeignKey("Id_Administrador");

                    b.HasOne("RCVUcab.Persistence.Entities.UsuarioEntity", "Perito")
                        .WithMany()
                        .HasForeignKey("PeritoId");

                    b.Navigation("Administrador");

                    b.Navigation("Perito");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.OrdenDeCompraEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.UsuarioEntity", "Administrador")
                        .WithMany("OrdenDeCompra")
                        .HasForeignKey("Id_Administrador");

                    b.HasOne("RCVUcab.Persistence.Entities.CotizacionEntity", "Id_Cotizacion")
                        .WithMany()
                        .HasForeignKey("Id_CotizacionId");

                    b.Navigation("Administrador");

                    b.Navigation("Id_Cotizacion");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaCotizacionEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.CotizacionEntity", "Cotizacion")
                        .WithMany("PiezaCotizacion")
                        .HasForeignKey("Id_Cotizacion");

                    b.HasOne("RCVUcab.Persistence.Entities.PiezaEntity", "Pieza")
                        .WithMany("PiezaCotizacion")
                        .HasForeignKey("Id_Pieza");

                    b.Navigation("Cotizacion");

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaMarcaEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.MarcaEntity", "Marca")
                        .WithMany("PiezaMarca")
                        .HasForeignKey("Id_Marca");

                    b.HasOne("RCVUcab.Persistence.Entities.PiezaEntity", "Pieza")
                        .WithMany("PiezaMarca")
                        .HasForeignKey("Id_Pieza");

                    b.Navigation("Marca");

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PolizaEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.UsuarioEntity", "Administrador")
                        .WithMany("Poliza")
                        .HasForeignKey("Id_Admin");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PropietarioEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.PolizaEntity", "Poliza")
                        .WithMany("Propietario")
                        .HasForeignKey("Id_Poliza");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.ProveedorEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.TallerEntity", "Taller")
                        .WithOne("Proveedor")
                        .HasForeignKey("RCVUcab.Persistence.Entities.ProveedorEntity", "TallerID");

                    b.Navigation("Taller");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.ProveedorMarcaEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.MarcaEntity", "Marca")
                        .WithMany("ProveedorMarca")
                        .HasForeignKey("Id_Marca");

                    b.HasOne("RCVUcab.Persistence.Entities.ProveedorEntity", "Proveedor")
                        .WithMany("ProveedorMarca")
                        .HasForeignKey("Id_Proveedor");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.VehiculoEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.MarcaEntity", "Marca")
                        .WithMany("Vehiculo")
                        .HasForeignKey("Id_Marca");

                    b.HasOne("RCVUcab.Persistence.Entities.PropietarioEntity", "Propietario")
                        .WithMany("Vehiculo")
                        .HasForeignKey("Id_Propietario");

                    b.Navigation("Marca");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.VehiculoIncidenteTallerEntity", b =>
                {
                    b.HasOne("RCVUcab.Persistence.Entities.IncidenteEntity", "Incidente")
                        .WithMany("VehiculoIncidenteTaller")
                        .HasForeignKey("Id_Incidente");

                    b.HasOne("RCVUcab.Persistence.Entities.PiezaEntity", "Pieza")
                        .WithMany("VehiculoIncidenteTaller")
                        .HasForeignKey("Id_Pieza");

                    b.HasOne("RCVUcab.Persistence.Entities.TallerEntity", "Taller")
                        .WithMany("VehiculoIncidenteTaller")
                        .HasForeignKey("Id_Taller");

                    b.HasOne("RCVUcab.Persistence.Entities.VehiculoEntity", "Vehiculo")
                        .WithMany("VehiculoIncidenteTaller")
                        .HasForeignKey("Id_Vehiculo");

                    b.Navigation("Incidente");

                    b.Navigation("Pieza");

                    b.Navigation("Taller");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.CotizacionEntity", b =>
                {
                    b.Navigation("PiezaCotizacion");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.IncidenteEntity", b =>
                {
                    b.Navigation("Cotizacion");

                    b.Navigation("VehiculoIncidenteTaller");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.MarcaEntity", b =>
                {
                    b.Navigation("PiezaMarca");

                    b.Navigation("ProveedorMarca");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PiezaEntity", b =>
                {
                    b.Navigation("PiezaCotizacion");

                    b.Navigation("PiezaMarca");

                    b.Navigation("VehiculoIncidenteTaller");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PolizaEntity", b =>
                {
                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.PropietarioEntity", b =>
                {
                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.ProveedorEntity", b =>
                {
                    b.Navigation("Cotizacion");

                    b.Navigation("ProveedorMarca");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.TallerEntity", b =>
                {
                    b.Navigation("CotizacionT");

                    b.Navigation("Proveedor");

                    b.Navigation("VehiculoIncidenteTaller");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Incidente");

                    b.Navigation("OrdenDeCompra");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("RCVUcab.Persistence.Entities.VehiculoEntity", b =>
                {
                    b.Navigation("VehiculoIncidenteTaller");
                });
#pragma warning restore 612, 618
        }
    }
}
